# Generated by Django 4.1.7 on 2023-02-28 18:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Aadhar_DB", "0010_remove_person_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=30)),
                ("otp", models.IntegerField(default=1111)),
                (
                    "date_joined",
                    models.DateField(
                        default=datetime.datetime(2023, 3, 1, 0, 27, 54, 300332)
                    ),
                ),
                ("email", models.CharField(default="none", max_length=10)),
                ("first_name", models.CharField(default="none", max_length=10)),
                ("last_name", models.CharField(default="none", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to="Aadhar_DB.aadhar",
                    ),
                ),
            ],
        ),
    ]
