# Generated by Django 4.1.7 on 2023-02-28 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("POAM_portal", "0003_alter_person_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="date_joined",
            field=models.DateField(
                default=datetime.datetime(2023, 3, 1, 1, 24, 15, 515706)
            ),
        ),
    ]
