# Generated by Django 4.1.7 on 2023-02-28 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("POAM_portal", "0008_alter_person_date_joined"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="date_joined",
            field=models.DateField(
                default=datetime.datetime(2023, 3, 1, 2, 24, 29, 648209)
            ),
        ),
    ]
