# Generated by Django 4.1.7 on 2023-03-01 17:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Aadhar_DB", "0012_user"),
        ("POAM_portal", "0012_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="People",
            new_name="Person",
        ),
    ]
