# Generated by Django 4.1.7 on 2023-04-18 19:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("POAM_portal", "0014_chain_of_title"),
    ]

    operations = [
        migrations.DeleteModel(
            name="chain_of_title",
        ),
    ]
