# Generated by Django 4.1.7 on 2023-02-28 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("Aadhar_DB", "0006_alter_person_date_joined"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("area", models.DecimalField(decimal_places=2, max_digits=5)),
                ("length", models.DecimalField(decimal_places=2, max_digits=5)),
                ("width", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "unit",
                    models.CharField(
                        choices=[("sqft", "Square.ft"), ("AC", "Acre")],
                        default="sqft",
                        max_length=4,
                    ),
                ),
                ("society_name", models.CharField(max_length=100)),
                ("society_rera_no", models.IntegerField()),
                ("plot_address", models.CharField(max_length=200)),
                ("north", models.CharField(max_length=30)),
                ("south", models.CharField(max_length=30)),
                ("east", models.CharField(max_length=30)),
                ("west", models.CharField(max_length=30)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plot_owner",
                        to="Aadhar_DB.aadhar",
                    ),
                ),
            ],
        ),
    ]
