# Generated by Django 4.1.7 on 2023-02-28 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Aadhar_DB", "0008_alter_person_date_joined"),
        ("MuncipalCorporation_DB", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plot",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plot_owner",
                to="Aadhar_DB.person",
            ),
        ),
    ]
