# Generated by Django 4.1.7 on 2023-02-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MuncipalCorporation_DB", "0002_alter_plot_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plot",
            name="area",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="plot",
            name="length",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="plot",
            name="width",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
