# Generated by Django 4.1.7 on 2023-04-18 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("MuncipalCorporation_DB", "0007_chain_of_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chain_of_title",
            name="owner_name",
        ),
        migrations.AddField(
            model_name="chain_of_title",
            name="plot",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plot_owner_name",
                to="MuncipalCorporation_DB.plot",
            ),
        ),
        migrations.AlterField(
            model_name="chain_of_title",
            name="selling_date",
            field=models.DateField(null=True),
        ),
    ]
