# Generated by Django 4.1.7 on 2023-04-18 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "MuncipalCorporation_DB",
            "0008_remove_chain_of_title_owner_name_chain_of_title_plot_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="chain_of_title",
        ),
    ]
