# Generated by Django 4.1.7 on 2023-03-01 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Bank_DB", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="acc_holder_name",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="receiver",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="sender",
        ),
    ]
