# Generated by Django 4.1.7 on 2023-03-02 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("POAM_portal", "0013_rename_people_person"),
        ("Bank_DB", "0002_remove_account_acc_holder_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="acc_holder_name",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="acc_holder",
                to="POAM_portal.person",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="receiver",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver",
                to="POAM_portal.person",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="sender",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender",
                to="POAM_portal.person",
            ),
        ),
    ]
