# Generated by Django 4.1.7 on 2023-04-18 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("POAM_portal", "0013_rename_people_person"),
        ("MuncipalCorporation_DB", "0009_delete_chain_of_title"),
        ("LegalComplaints_DB", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="plot_agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchaser_sign", models.BooleanField(default=False)),
                ("buyer_sign", models.BooleanField(default=False)),
                ("total_amount", models.BigIntegerField()),
                ("agreement_duration", models.DateField()),
                ("purchaser_witness_sign", models.BooleanField(default=False)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plot_buyer",
                        to="POAM_portal.person",
                    ),
                ),
                (
                    "buyer_witness",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plot_buyer_witness",
                        to="POAM_portal.person",
                    ),
                ),
                (
                    "plot_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plot_details",
                        to="MuncipalCorporation_DB.plot",
                    ),
                ),
                (
                    "purchaser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plot_purchaser",
                        to="POAM_portal.person",
                    ),
                ),
                (
                    "purchaser_witness",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plot_purchaser_witness",
                        to="POAM_portal.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="proxy_agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proxy_agreement_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prxy_agrmnt",
                        to="Sarathi_DB.plot_agreement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plot_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="master_plot_details",
                        to="MuncipalCorporation_DB.plot",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="chain_of_title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ownership_date", models.DateField()),
                ("selling_date", models.DateField(blank=True, null=True)),
                (
                    "plot",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plot_owner_name",
                        to="MuncipalCorporation_DB.plot",
                    ),
                ),
                (
                    "title_owner",
                    models.ManyToManyField(
                        default=None,
                        related_name="title_chain_owner_details",
                        to="POAM_portal.person",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="blacklist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_blocked", models.BooleanField(default=False)),
                (
                    "Property_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proprty_case",
                        to="LegalComplaints_DB.complaint",
                    ),
                ),
            ],
        ),
    ]
