# Generated by Django 4.1.7 on 2023-02-28 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("MuncipalCorporation_DB", "0004_alter_plot_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plot_details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_blocked", models.BooleanField(default=False)),
                (
                    "details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plot_details",
                        to="MuncipalCorporation_DB.plot",
                    ),
                ),
            ],
        ),
    ]
