# Generated by Django 4.1.7 on 2023-04-19 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("POAM_portal", "0015_delete_chain_of_title"),
        ("Sarathi_DB", "0002_plot_details_sharing"),
    ]

    operations = [
        migrations.AddField(
            model_name="plot_details",
            name="buyer",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plot_buyer_details",
                to="POAM_portal.person",
            ),
        ),
    ]
