# Generated by Django 4.1.7 on 2023-04-18 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Sarathi_DB", "0003_alter_plot_details_details_plot_agreement"),
    ]

    operations = [
        migrations.CreateModel(
            name="proxy_agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proxy_agreement_details",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prxy_agrmnt",
                        to="Sarathi_DB.plot_agreement",
                    ),
                ),
            ],
        ),
    ]
