# Generated by Django 4.1.7 on 2023-04-18 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("MuncipalCorporation_DB", "0009_delete_chain_of_title"),
        ("Sarathi_DB", "0004_proxy_agreement"),
    ]

    operations = [
        migrations.CreateModel(
            name="chain_of_title",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("onwership_date", models.DateField()),
                ("selling_date", models.DateField(null=True)),
                (
                    "plot",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plot_owner_name",
                        to="MuncipalCorporation_DB.plot",
                    ),
                ),
            ],
        ),
    ]
