# Generated by Django 4.1.7 on 2023-02-28 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Aadhar_DB", "0002_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="Aadhar_DB.aadhar",
            ),
        ),
    ]
