# Generated by Django 4.1.7 on 2023-02-28 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Aadhar_DB", "0003_alter_user_username"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Person",
        ),
    ]
