# Generated by Django 4.1.7 on 2023-02-28 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Aadhar_DB", "0004_rename_user_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="date_joined",
            field=models.DateField(
                default=datetime.datetime(2023, 2, 28, 22, 6, 7, 835980)
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="email",
            field=models.CharField(default="none", max_length=10),
        ),
        migrations.AddField(
            model_name="person",
            name="first_name",
            field=models.CharField(default="none", max_length=10),
        ),
        migrations.AddField(
            model_name="person",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="person",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person",
            name="last_name",
            field=models.CharField(default="none", max_length=10),
        ),
    ]
