# Generated by Django 4.1.7 on 2023-02-28 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Aadhar_DB", "0009_alter_person_date_joined"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="username",
        ),
    ]
