# Generated by Django 4.1.7 on 2023-02-28 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Aadhar_DB", "0010_remove_person_username"),
        ("MuncipalCorporation_DB", "0004_alter_plot_owner"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Person",
        ),
    ]
